/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dae2fd",
        "outline-variant": "#c6c6cd",
        "secondary": "#006a61",
        "error": "#ba1a1a",
        "on-secondary-container": "#006f66",
        "tertiary-container": "#2a1700",
        "error-container": "#ffdad6",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#653e00",
        "surface": "#f8f9ff",
        "on-surface-variant": "#45464d",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#86f2e4",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "surface-tint": "#565e74",
        "primary": "#000000",
        "on-primary-fixed": "#131b2e",
        "surface-container-high": "#dce9ff",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#6bd8cb",
        "primary-fixed-dim": "#bec6e0",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#2a1700",
        "on-primary-container": "#7c839b",
        "tertiary": "#000000",
        "surface-container-lowest": "#ffffff",
        "outline": "#76777d",
        "on-secondary-fixed": "#00201d",
        "on-secondary-fixed-variant": "#005049",
        "inverse-surface": "#213145",
        "on-primary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "inverse-primary": "#bec6e0",
        "on-error": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "background": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-container": "#131b2e",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "on-tertiary-container": "#b87500",
        "surface-container-highest": "#d3e4fe"
      },
      fontFamily: {
        body: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [],
}
